### PR TITLE
Explore Repackaging  [work in progress]

### PR DESCRIPTION
**Pull request by teesloane**
- move all source code into a `src` folder.
  - not sure if this is the most logical way to do it, but if files are
  not in packages it is required to run `go run *.go` to run the entire
  project.
  - in this case, if tests are also in that directory it seems to bork
  things a bit. So for now, I moved tests into a seperate directory. I
  don't know how to manage that yet (I haven't even figured out how to
  run tests yet.
- all code belongs to package main
- this removes imports from other packages
- Renamed files to be more descriptive now that they are not name spaced
to a package. exmaple: `messages.Load` -> `LoadMessages`
- created a helper function for checking that the right arguments are
passed in the commandline os.Args[0].

**Screenshot**

image

### CODE REVIEW

**Comment by teesloane** [comment]
Any thoughts on this structure @jbydeley ? I feel like maybe putting it under `src` isn't very goish ... but then if we have everything at the top level I guess we'd have to right some regex for only running the go files we want, instead of using `go run *.go`.

although perhaps we could also toss the tests into a folder... [sarama](https://github.com/Shopify/sarama) has a folder called `mocks` at the top level which might be for tests.

Thoughts?

**Comment by jbydeley** [comment]
So I don't have a lot of time at the moment but there is a reverse way to do this that is more Goish. Everything is top of the root except for main which is under ./cmd/beacon/main.go 
I'm on my phone atm but this afternoon I should have some time.

**Comment by teesloane** [comment]
ohhhh sweet. Thanks for the tip! I can rearrange this now!

**Comment by teesloane** [comment]
Ok, so I've been reading a lot of stuff on how Go handles packaging stuff. It seems that some people do things differently.

Correct me if I'm mistaken, but I think the first question we have to ask is: _is this a library_ (ie. something people would `go get`?) _or is this a self contained package_.

I believe we are the latter – I can't think of a reason why someone would install beacon as a dependency in their project -- we are just building a command line tool. This might be some basic / obvious Go stuff - so correct me if I'm mistaken.

Moving on — in the case that this is a self contained package... what is the standard here? Do we need to name all files specific to beacon into a package named `package beacon`? -- afaik, this is only really necessary again as a library.

I don't really understand the use of `cmd/beacon/main.go`.

Another note -- if everything is at the top level in a `package main` then we won't be able to (as easily) use `go run main.go` (which is what I've been doing). I'm pretty new to working with a compiled language - so I'm guessing it's the norm to _actually compile your code_ and then run it, something like:

`go build && ./beacon add ...` etc. 

What do you think of this dev env? I think I'll leave this decision up to you — my goal has been to get acclimatized to the Golang environment, and so I'm happy if we can get something as standard as possible. With that said, if there's still some organizing to do with this new structure, you could just commit directly to this branch (I made you a contributor, so that should be feasible).

edit: updated screenshot:

image

**Comment by jbydeley** [comment]
So I sit corrected. You are correct in that the `/cmd/beacon/main.go` is generally used for libraries, I like it because I can go into that directory and continue to run `go run main.go`. After looking over what we currently have in godoc.org again, we could spruce up main.go, keep everything in their respective directories and just add additional information as well as [Examples](https://blog.golang.org/examples). Sorry, I haven't really worked on Go code with anyone else before so I don't know documentation and structure very well.

**Comment by jbydeley** [comment]
I should also say, if you are curious what your godoc will look like before merging, you can run `godoc -http=":6060"` to run it locally on port 6060.

**Comment by teesloane** [comment]
No need to apologize - this is my first real time running a project in Go. 

So, going forward, let's keep things flat, top level, with no `cmd/beacon/main.go`. 

This article was a [useful read](https://blog.golang.org/godoc-documenting-go-code) for learning about writing docs. It also mentions:

> They  [comments] can also be detailed like the [gob package's](https://golang.org/src/encoding/gob/doc.go) overview. That package uses another convention for packages that need large amounts of introductory documentation: the package comment is placed in its own file, doc.go, which contains only those comments and a package clause.

So, we can create a `doc.go` to get a good overview of the entire project. 

Also, having some examples eventually, would be pretty cool.

**Comment by teesloane** [comment]
Updated docs to reflect new build / dev process.

**Pull request merged**
